# Generated by Django 5.0.3 on 2024-03-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_alter_recipe_time_for_cooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_for_cooking',
            field=models.IntegerField(),
        ),
    ]
